title: mxkkkk                 # 导航栏左侧用户名，首页姓名
email: w19091@outlook.com
description: mxkkkk 的个人博客
signature: 我们一路奋战，不是为了改变世界，而是为了让世界不再改变我们。 # 首页个性签名
lang: zh-CN
url: "https://mxkfemkkk.github.io"
baseurl: ""                   # 用户站点必须为空字符串
encoding: utf-8
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
permalink: /:year/:month/:day/:title/
# Gitalk 评论区配置（在 GitHub 上创建 OAuth App 后填入）
gitalk:
  proxy: "https://gitalk-proxy.zhangmaixuan.workers.dev/access_token" # 代理地址，解决 Gitalk 评论区跨域问题
  clientID: "Ov23lil0N3VAXWbgSIvK"        # OAuth App 的 Client ID
  clientSecret: "dad7deef634de28defa893ddcc05f0aef74b665b"    # OAuth App 的 Client Secret
  repo: "gittalk"            # 存放评论 issue 的仓库名（如 mxkfemkkk.github.io）
  owner: "mxkfemkkk"           # 仓库所有者（GitHub 用户名）
  admin: "mxkfemkkk"           # 仓库管理员（GitHub 用户名）
date_format: "%Y-%m-%d"
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
