title: mxkkkk                 # 导航栏左侧用户名，首页姓名
email: w19091@outlook.com
description: mxkkkk 的个人博客
signature: 我们一路奋战，不是为了改变世界，而是为了让世界不再改变我们。 # 首页个性签名
lang: zh-CN
url: "https://mxkfemkkk.github.io"
baseurl: ""                   # 用户站点必须为空字符串
encoding: utf-8
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
permalink: /:year/:month/:day/:title/
date_format: "%Y-%m-%d"
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
